services:
  api:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    container_name: cv-assistant-api-prod
    restart: always
    env_file:
      - ../../.env.production
    ports:
      - "4003:4003"
    networks:
      - cv_prod_network

networks:
  cv_prod_network:
    driver: bridge
